---
- name: Add go development repository
  zypper_repository:
    repo: 'https://download.opensuse.org/repositories/devel:/languages:/go/SLE_15_SP2'
    auto_import_keys: yes
    name: "go.repo"
    state: present
  when:
    - ansible_distribution == "SLES"
    - ansible_distribution_major_version == "15"

- name: Install telegraf
  zypper:
    name: telegraf
    state: present
    update_cache: yes
  when: ansible_distribution == "SLES"

- name: Start service telegraf, if not started
  ansible.builtin.service:
    name: telegraf
    state: started
