---
- name: Add go development repository
  zypper_repository:
    repo: 'https://download.opensuse.org/repositories/devel:/languages:/go/SLE_15_SP2'
    auto_import_keys: yes
    name: "go.repo"
    state: present
  when:
    - ansible_distribution == "SLES"
    - ansible_distribution_major_version == "15"

- name: Install telegraf
  zypper:
    name: telegraf
    state: present
    update_cache: yes
  when: ansible_distribution == "SLES"

- name: Create telegraf conf directory
  file:
    path: /etc/telegraf.d
    state: directory
    mode: '0755'

- name: Install telegraf config
  copy:
    src: 'telegraf.conf'
    dest: '/etc/telegraf/'
    owner: root
    group: root
    mode: 0755
  notify: "Restart Telegraf"

- name: Copy telegraf input/output configs
  copy:
    src: '{{item}}'
    dest: '/etc/telegraf/telegraf.d/'
    owner: root
    group: root
    mode: 0644
  loop:
    - prometheus_output.conf
    - system_input.conf
  notify: "Restart Telegraf"

- name: Start service telegraf, if not started
  ansible.builtin.service:
    name: telegraf
    state: started
