---
- name: Edit and apply neconfig
  lineinfile:
    path: /etc/sysconfig/network/config
    regexp: '^NETCONFIG_DNS_STATIC_SEARCHLIST=\"\"'
    line: "NETCONFIG_DNS_STATIC_SEARCHLIST=\"{{ domain_name }}\""
    state: present
  notify: 'force apply netconfig changes'

