---
# Apply common configuration to all hosts
- hosts: all
  become: yes
  roles:
  - ../roles/common
  - ../roles/monitoring/telegraf

- hosts: shared_kosikca_hosts
  become: yes
  roles:
  - ../roles/shared/kosikca

- hosts: shared_prometheus_hosts
  become: yes
  roles:
  - ../roles/shared/prometheus

- hosts: shared_promxy_hosts
  become: yes
  roles:
  - ../roles/shared/promxy
