---
# Apply common configuration to all hosts
- hosts: all
  become: yes
  roles:
  - ../roles/common
  - ../roles/monitoring/telegraf

- hosts: sap_cz_sandbox_hana_db_hosts
  become: yes
  roles:
  - ../roles/sap/cz/sandbox/hanadb

- hosts: sap_cz_sandbox_nfs_hosts
  become: yes
  roles:
  - ../roles/sap/cz/sandbox/nfs

- hosts: sap_cz_sandbox_dialog_hosts
  become: yes
  roles:
  - ../roles/sap/cz/sandbox/dialog
  - ../roles/monitoring/telegraf

- hosts: sap_cz_sandbox_ascs_hosts
  become: yes
  roles:
  - ../roles/sap/cz/sandbox/ascs

