---
# Apply common configuration to all hosts
- hosts: all
  become: yes
  roles:
  - ../roles/common
    #  - ../roles/monitoring/telegraf

- hosts: sap_cz_pred_hana_db_hosts
  become: yes
  roles:
  - ../roles/sap/cz/pred/hanadb

- hosts: sap_cz_pred_nfs_hosts
  become: yes
  roles:
  - ../roles/sap/cz/pred/nfs

- hosts: sap_cz_pred_dialog_hosts
  become: yes
  roles:
  - ../roles/sap/cz/pred/dialog

- hosts: sap_cz_pred_ascs_hosts
  become: yes
  roles:
  - ../roles/sap/cz/pred/ascs

