---
# Apply common configuration to all hosts
- hosts: all
  become: yes
  roles:
  - ../roles/common

- hosts: sap_cz_test_hana_db_hosts
  become: yes
  roles:
  - ../roles/sap/cz/test/hanadb

- hosts: sap_cz_test_dialog_hosts
  become: yes
  roles:
  - ../roles/sap/cz/test/dialog

- hosts: sap_cz_test_pdf_hosts
  become: yes
  roles:
  - ../roles/sap/cz/test/pdf

